name: "Build Sphinx Docs: Build and update"

on:
  push:
    branches:
        - main
        - develop

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Prepare Subfolder Deployment
      run: |
        # Create a tempory export directory
        mkdir -p out_dist

        if [ "${{ github.ref_name }}" = "main" ]; then
          cp -r ./* out_dist/ || true
        else
          mkdir -p out_dist/${{ github.ref_name }}
          cp -r ./* out_dist/${{ github.ref_name }}/ || true
        fi

        # Clean up the output folder from copying itself if necessary
        rm -rf out_dist/out_dist

    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        #publish_dir: docs/build/html
        publish_dir: ./out_dist
        publish_branch: gh-pages
        keep_files: true
